openapi: "3.0.0"
info:
  title: "XSS-Test"
  version: "1.0.0"
  description: "'<img src=x onerror=alert('XSS_from_YAML')>"
paths:
  /test:
    get:
      summary: "Test"
      responses:
        '200':
          description: "OK"
